- yum:
    name: ansible
    state: absent

- yum:
    name: "{{ item }}"
    state: present
    with_items:
      - git
      - python2
      - python2-devel
      - gcc

- pip:
    name: "{{ item }}"
    state: present
    with_items:
      - paramiko
      - PyYAML
      - Jinja2
      - httplib2
      - six

- git:
     repo: git://github.com/ansible/ansible.git
     recursive: yes
     dest: "{{ prefix }}"

- template:
    src: "ansible.sh.j2"
    dest: "/etc/profile.d/ansible.sh"
    mode: 0644


