- yum:
    name: ansible
    state: absent

- git:
     repo: git://github.com/ansible/ansible.git
     recursive: yes
     dest: "{{ prefix }}"

- template:
    src: "templates/ansible.sh.j2"
    dest: "/etc/profile.d/ansible.sh"

