- name: install ansible from ansible git repo
  include: tasks/install_ansible.yml
  when: install_latest

- name: install ansible from epel repo
  include: tasks/install_epel_ansible.yml
  when: not install_latest
